services:
  database:
    image: postgres:13.22-trixie
    container_name: database_fincheck
    restart: always
    env_file:
      - ..database.env
    ports:
      - "5432:5432"

  api:
    container_name: api_fincheck
    env_file:
      - ..api.env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - database

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana_fincheck
    restart: unless-stopped
    env_file:
      - ..grafana.env
    ports:
      - "3005:3000"
    depends_on:
      - database
    volumes:
      - 'grafana_storage:/var/lib/grafana'

volumes:
  grafana_storage: {}